// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectoAvance1.Data;

namespace ProjectoAvance1.Migrations.ProjectDb
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20220406211634_TablaProductos")]
    partial class TablaProductos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectoAvance1.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreCategoria = "Corte y Grabado Laser"
                        },
                        new
                        {
                            Id = 2,
                            NombreCategoria = "Lamparas Led"
                        },
                        new
                        {
                            Id = 3,
                            NombreCategoria = "Corte y Grabado CNC"
                        },
                        new
                        {
                            Id = 4,
                            NombreCategoria = "Rompecabezas"
                        });
                });

            modelBuilder.Entity("ProjectoAvance1.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "GuestBook-1",
                            Descripcion = "Libro de Invitados",
                            Disponible = true,
                            Foto = "~/img/productos/1/1.jpg",
                            IdCategoria = 1,
                            Precio = 10m
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "Coaster-1",
                            Descripcion = "Portavasos personalizados",
                            Disponible = true,
                            Foto = "~/img/productos/1/2.jpg",
                            IdCategoria = 1,
                            Precio = 10m
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "Keychain-1",
                            Descripcion = "Lalveros personalizados",
                            Disponible = true,
                            Foto = "~/img/productos/1/3.jpg",
                            IdCategoria = 1,
                            Precio = 5m
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "Nameboard-1",
                            Descripcion = "Nombres personalizados",
                            Disponible = true,
                            Foto = "~/img/productos/1/4.jpg",
                            IdCategoria = 1,
                            Precio = 10m
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "Led-1",
                            Descripcion = "Lampara Led",
                            Disponible = true,
                            Foto = "~/img/productos/2/5.jpg",
                            IdCategoria = 2,
                            Precio = 25m
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "Led-2",
                            Descripcion = "Lampara Led Luna",
                            Disponible = true,
                            Foto = "~/img/productos/1/2.jpg",
                            IdCategoria = 2,
                            Precio = 25m
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "Led-3",
                            Descripcion = "Lampara Led Darth Vader",
                            Disponible = true,
                            Foto = "~/img/productos/1/3.jpg",
                            IdCategoria = 2,
                            Precio = 25m
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "CNC-1",
                            Descripcion = "Letras",
                            Disponible = true,
                            Foto = "~/img/productos/3/8.jpg",
                            IdCategoria = 3,
                            Precio = 10m
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "CNC-2",
                            Descripcion = "Trineo de Santa",
                            Disponible = true,
                            Foto = "~/img/productos/3/9.jpg",
                            IdCategoria = 3,
                            Precio = 50m
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "CNC-3",
                            Descripcion = "Tabla para picar",
                            Disponible = true,
                            Foto = "~/img/productos/3/10.jpg",
                            IdCategoria = 3,
                            Precio = 10m
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "CNC-4",
                            Descripcion = "Tablas personalizadas",
                            Disponible = true,
                            Foto = "~/img/productos/3/11.jpg",
                            IdCategoria = 3,
                            Precio = 25m
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "PZ-1",
                            Descripcion = "Rompecabeza Caballo",
                            Disponible = true,
                            Foto = "~/img/productos/4/12.jpg",
                            IdCategoria = 4,
                            Precio = 10m
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "PZ-2",
                            Descripcion = "Rompecabeza colores",
                            Disponible = true,
                            Foto = "~/img/productos/4/13.jpg",
                            IdCategoria = 4,
                            Precio = 50m
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "PZ-3",
                            Descripcion = "Rompecabeza Abeja",
                            Disponible = true,
                            Foto = "~/img/productos/4/14.jpg",
                            IdCategoria = 4,
                            Precio = 10m
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "PZ-4",
                            Descripcion = "Rompecabeza Nave Espacial",
                            Disponible = true,
                            Foto = "~/img/productos/4/15.jpg",
                            IdCategoria = 4,
                            Precio = 25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
